Adding TAF PROD team users to github listed in DBDAART-4917
Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python pull request #107
Opened 2023-11-21 16:44 UTC by FICU-tensileai

## What is this and why are we doing it?
In preparation for TAF PROD, we're making a modification to the CODEOWNERS file to add the TAF PROD users.

* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4917

## What are the security implications from this change?
There is always a security concern when modifying the CODEOWNERS file but we've recently changed the process to have 2 reviewers on a PR and the users added are part of the TAF project and given to us as stated in DBDAART-4917. There is one user who does not yet have a github account and will need to go through the project to get the job code and be added and approved with an additional PR from the TAF PROD team.

## How did I test this?
Verified the usernames from 4917

## Should there be new or updated documentation for this change? (Be specific.)
No.

## PR Checklist
- [x] The JIRA ticket number and a short description is in the subject line
- [x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2023-11-21 17:50 UTC, RIE9-adhoc commented
@FICU-tensileai 
Could you confirm that Heidi is supposed to be missing from this PR?
I went to Xiao Barry's page: https://github.com/xiaobarry, and `BRSC-Mathematica` is listed. Should xiaobarry and fumanjie have their EUA-Company name combo specified?

2023-11-21 17:52 UTC, C1KB-tensileai requested changes
@FICU-tensileai please look at my comment on the error GH raised for Xiao and Manjie

2023-11-21 17:52 UTC, C1KB-tensileai commented on .github/CODEOWNERS
> +* @C1KB-tensileai @FICU-tensileai @AKDO-slalom @THOA-slalom @GPEC-adhoc @TUAS-forpeople @BKY3-forpeople @VPAI-bixal @MIPI-forpeople @GHHZ-bixal @RIE9-adhoc @a-pfeiffer @XiaoBarry @alihashmi-wh @fuman
@FICU-tensileai looks like we have some issues with the user names supplied for Xiao and Manjie.
Trying to tag them in this comment makes me believe Xiao should be `BRSC-Mathematica`. I think Manjie's user name is correct, but he might need to request access from Jose Alarcon (assuming he has the correct job codes?)

2023-11-21 18:11 UTC, FICU-tensileai commented
Well, I didn't even realize that it parsed it like that! The users show up but it appears they will need to be in the proper group(s) via job codes, etc. Will put this on-hold until then.

2023-11-21 18:48 UTC, FICU-tensileai commented
Ok, I've send the instructions over to those who still need to get into the CMS github groups. We'll need to wait before we can correct this file.

2023-12-07 16:11 UTC, FICU-tensileai commented
The decision is to put the 2 codeowners that have accounts to LIVE now and they will add the others on the TAF PROD team when ready.

2023-12-07 16:21 UTC, TUAS-forpeople approved these changes

2023-12-08 16:43 UTC, merged